# Generated by Django 5.1.4 on 2024-12-17 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Email Address')),
                ('Fname', models.CharField(max_length=25, verbose_name='First Name')),
                ('Mname', models.CharField(blank=True, max_length=25, null=True, verbose_name='Middle Name')),
                ('Lname', models.CharField(max_length=25, verbose_name='Last Name')),
                ('bio', models.TextField(blank=True, max_length=150, null=True, verbose_name='Basic Info')),
                ('department', models.CharField(choices=[('Computing', 'Computing'), ('Business', 'Business'), ('Engineering', 'Engineering'), ('Others', 'Others')], max_length=50)),
                ('Reg_no', models.CharField(max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('Gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('staff', models.BooleanField(default=False)),
                ('dob', models.DateField()),
                ('dp', models.CharField(default='avatar.png', null=True)),
                ('Role', models.CharField(default='Student', max_length=50)),
                ('Address', models.CharField(max_length=255)),
                ('groups', models.ManyToManyField(blank=True, related_name='user_set', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='user_set', to='auth.permission')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
